### PR TITLE
We should consider making a new file style.css

### PR DESCRIPTION
**Pull request by shubhamispandey**
Yes We should make a new file for styling

### CODE REVIEW

**Comment by occtapus** [comment]
Can you provide a description for this and why should we consider it ?

**Comment by shubhamispandey** [comment]
Ya sure @occtapus we need to make a new file in order to make it a      #####component-based design and also write a readable code

**Comment by occtapus** [comment]
Feels good to me

**Comment by occtapus** [comment]
we are merging ur request , Now onwards we will be having new styles in **proposed file**

**Comment by shubhamispandey** [comment]
Thanks so much, **@occtapus**. I feel glad to help u.

**Pull request merged**
